# Generated by Django 4.2.27 on 2026-01-18 10:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.CharField(help_text='API path called', max_length=255)),
                ('method', models.CharField(help_text='HTTP method (GET, POST, etc.)', max_length=10)),
                ('query_params', models.JSONField(default=dict, help_text='Filter/search parameters')),
                ('duration_ms', models.PositiveIntegerField(help_text='Response time in milliseconds')),
                ('status_code', models.PositiveSmallIntegerField(help_text='HTTP response status')),
                ('result_count', models.IntegerField(default=-1, help_text='Number of results returned (-1 if N/A)')),
                ('error_message', models.TextField(blank=True, help_text='Error details if failed', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='Client user agent', max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When request occurred')),
            ],
            options={
                'verbose_name': 'Query Log',
                'verbose_name_plural': 'Query Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='querylog_timestamp_idx'), models.Index(fields=['status_code'], name='querylog_status_idx'), models.Index(fields=['duration_ms'], name='querylog_duration_idx'), models.Index(fields=['endpoint'], name='querylog_endpoint_idx')],
            },
        ),
    ]
